# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 201736a28bbe5729a67aacf807803112f7103b1d9fa40a85f8c74af2f745f6f33dbe3cc0459f9051282089d6399f8b1978adc72f7dd7ab8f5297539cd222dbe6

test:
  secret_key_base: 5b6f8c55d51aa30c6ca238f36696b8c2ae90e4344e48e4d3f33de79da2563d593c010066045d6222a48f582dc96f70e2ad614fb7eb9c1a5edd47dc4d3122187a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
