redis:
  client:
    size: 1
    namespace: 'g-indexer'
  server:
    size: 5
    namespace: 'g-indexer'

exception_notification:
  email_config:
    email_prefix: "[GIndexerApp]"
    sender_address: "'Notifier' <notifier@app32547894.mailgun.org>"
    exception_recipients:
      - balaban.petr@gmail.com

mailgun:
  authentication: plain
  address: smtp.mailgun.org
  port: 587
  domain: app32547894.mailgun.org
  user_name: postmaster@app32547894.mailgun.org
  password: replace_me

basic_auth:
  enabled: false
